In [1]:
%store -r X
X

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X48,X49,X50,X51,X52,X53,X54,X55,X56,X57
0,0.00,0.00,4.34,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.000,0.0,1.342,0.000,0.000,1.200,2,12
1,0.00,0.56,0.56,0.00,1.12,0.56,2.25,0.00,0.00,0.56,...,0.0,0.0,0.083,0.0,0.503,0.000,0.083,16.304,148,375
2,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.000,0.0,0.000,0.000,0.000,1.000,1,5
3,0.64,0.00,0.64,0.00,1.93,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.000,0.0,0.462,0.370,0.000,2.440,22,122
4,0.58,0.00,0.00,35.46,0.58,0.00,0.58,0.58,0.00,0.00,...,0.0,0.0,0.000,0.0,0.239,0.239,0.000,3.338,123,207
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3905,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.000,0.0,0.000,0.000,0.000,1.714,4,12
3906,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.000,0.0,0.000,0.000,0.000,2.000,3,4
3907,0.12,0.00,0.12,0.00,0.00,0.25,0.00,0.00,0.00,0.00,...,0.0,0.0,0.093,0.0,0.023,0.000,0.000,1.247,5,131
3908,0.00,0.00,0.00,0.00,0.00,0.00,0.00,3.12,0.00,0.00,...,0.0,0.0,0.198,0.0,0.198,0.198,0.000,3.857,25,81
3909,0.96,0.00,0.48,0.00,0.00,0.96,0.00,0.00,0.48,0.00,...,0.0,0.0,0.818,0.0,0.175,0.467,0.116,9.560,259,717

In [2]:
%store -r y
y

      Y
0     0
1     1
2     0
3     1
4     1
...  ..
3905  0
3906  0
3907  0
3908  1
3909  1

[3910 rows x 1 columns]

In [3]:
%store -r feature_set
feature_set

['X3',
 'X5',
 'X6',
 'X7',
 'X8',
 'X9',
 'X10',
 'X11',
 'X12',
 'X16',
 'X17',
 'X18',
 'X19',
 'X21',
 'X23',
 'X24',
 'X25',
 'X26',
 'X27',
 'X28',
 'X37',
 'X42',
 'X45',
 'X46',
 'X50',
 'X52',
 'X53',
 'X55',
 'X56',
 'X57']

In [31]:
import pandas as pd
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from keras.wrappers.scikit_learn import KerasClassifier
from keras.models import Sequential
from keras.layers import Dense, Activation, Embedding, Flatten, LeakyReLU, BatchNormalization, Dropout
from keras.activations import relu, sigmoid
import warnings
warnings.filterwarnings('ignore')

Decision tree

In [5]:
tuned_parameters = [{'criterion' : ('gini', 'entropy'), 'max_depth' : [2,3,4,5,6,7,8,9,10]}] 
dt_model = GridSearchCV(DecisionTreeClassifier(), tuned_parameters, scoring='f1', cv=5)
dt_model.fit(X, y)
print(dt_model.best_estimator_)
print(dt_model.best_score_)

DecisionTreeClassifier(criterion='entropy', max_depth=10)
0.9020421576805943

In [6]:
tuned_parameters = [{'criterion' : ('gini', 'entropy'), 'max_depth' : [2,3,4,5,6,7,8,9,10]}] 
dt_model_actual = GridSearchCV(DecisionTreeClassifier(), tuned_parameters, scoring='f1', cv=5)
dt_model_actual.fit(X[feature_set], y)
print(dt_model_actual.best_estimator_)
print(dt_model_actual.best_score_)

DecisionTreeClassifier(criterion='entropy', max_depth=9)
0.8989495342015316

Random Forest

In [28]:
tuned_parameters = [{'criterion' : ('gini', 'entropy'), 'max_depth' : [2,3,4,5,6,7,8,9,10], 'n_estimators' : [10,20,30,40,50]}] 
rf_model = GridSearchCV(RandomForestClassifier(), tuned_parameters, scoring='f1', cv=5)
rf_model.fit(X, y)
print(rf_model.best_estimator_)
print(rf_model.best_score_)

RandomForestClassifier(max_depth=10, n_estimators=30)
0.9226535448472596

In [29]:
tuned_parameters = [{'criterion' : ('gini', 'entropy'), 'max_depth' : [2,3,4,5,6,7,8,9,10], 'n_estimators' : [10,20,30,40,50]}] 
rf_model_actual = GridSearchCV(RandomForestClassifier(), tuned_parameters, scoring='f1', cv=5)
rf_model_actual.fit(X[feature_set], y)
print(rf_model_actual.best_estimator_)
print(rf_model_actual.best_score_)

RandomForestClassifier(criterion='entropy', max_depth=10, n_estimators=40)
0.9247094209852802

Neural networks

In [15]:
def create_model(layers, activation):
    model = Sequential()
    for i, nodes in enumerate(layers):
        if i==0:                                                                
            model.add(Dense(nodes,input_dim=X.shape[1]))
            model.add(Activation(activation))
            model.add(Dropout(0.3))
        else:                                                                    
            model.add(Dense(nodes))
            model.add(Activation(activation))
            model.add(Dropout(0.3))
            
    model.add(Dense(units = 1, kernel_initializer= 'glorot_uniform', activation = 'sigmoid')) 
    
    model.compile(optimizer='adam', loss='binary_crossentropy')
    return model

In [16]:
ann_model = KerasClassifier(build_fn=create_model, verbose=0)

In [17]:
layers = [[16], [32, 16], [64, 32, 16]]
activations = ['sigmoid', 'relu']
param_grid = dict(layers=layers, activation=activations, batch_size = [128, 256], epochs=[30])
grid = GridSearchCV(estimator = ann_model, param_grid = param_grid, scoring = 'f1', cv = 5)

In [18]:
grid_result = grid.fit(X, y)

25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 826us/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 2ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 914us/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 884us/step
25/25 [==============================] - 0s 783us/step
25/25 [==============================] - 0s 917us/step
25/25 [==============================] - 0s 498us/step
25/25 [==============================] - 0s 713us/step
25/25 [==============================] - 0s 619us/step
25/25 [==============================] - 0s 388us/step
25/25 [==============================] - 0s 340us/step
25/25 [==============================] - 0s 794us/step
25/25 [==============================] - 0s 853us/step
25/25 [==============================] - 0s 395us/step
25/25 [==============================] - 0s 876us/step
25/25 [==============================] - 0s 914us/step
25/25 [==============================] - 0s 773us/step
25/25 [==============================] - 0s 737us/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 294us/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 941us/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 2ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 2ms/step
25/25 [==============================] - 0s 2ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 2ms/step
25/25 [==============================] - 0s 2ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 903us/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 2ms/step
25/25 [==============================] - 0s 984us/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 997us/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 2ms/step

In [19]:
print(grid_result.best_score_, grid_result.best_params_)

0.914600063733128 {'activation': 'sigmoid', 'batch_size': 128, 'epochs': 30, 'layers': [64, 32, 16]}

In [21]:
def create_model_actual(layers, activation):
    model = Sequential()
    for i, nodes in enumerate(layers):
        if i==0:                                                                
            model.add(Dense(nodes,input_dim=X[feature_set].shape[1]))
            model.add(Activation(activation))
            model.add(Dropout(0.3))
        else:                                                                    
            model.add(Dense(nodes))
            model.add(Activation(activation))
            model.add(Dropout(0.3))
            
    model.add(Dense(units = 1, kernel_initializer= 'glorot_uniform', activation = 'sigmoid')) 
    
    model.compile(optimizer='adam', loss='binary_crossentropy')
    return model

In [22]:
ann_model_actual = KerasClassifier(build_fn=create_model_actual, verbose=0)

In [23]:
layers = [[16], [32, 16], [64, 32, 16]]
activations = ['sigmoid', 'relu']
param_grid = dict(layers=layers, activation=activations, batch_size = [128, 256], epochs=[30])
grid_actual = GridSearchCV(estimator = ann_model_actual, param_grid = param_grid, scoring = 'f1', cv = 5)

In [24]:
grid_result_actual = grid_actual.fit(X[feature_set], y)

25/25 [==============================] - 0s 971us/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 913us/step
25/25 [==============================] - 0s 840us/step
25/25 [==============================] - 0s 970us/step
25/25 [==============================] - 0s 899us/step
25/25 [==============================] - 0s 956us/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 940us/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 2ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 2ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 2ms/step
25/25 [==============================] - 0s 2ms/step
25/25 [==============================] - 0s 2ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 2ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 2ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 959us/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 2ms/step
25/25 [==============================] - 0s 2ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 2ms/step
25/25 [==============================] - 0s 974us/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 2ms/step
25/25 [==============================] - 0s 896us/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 993us/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 2ms/step
25/25 [==============================] - 0s 1ms/step
25/25 [==============================] - 0s 962us/step
25/25 [==============================] - 0s 2ms/step
25/25 [==============================] - 0s 971us/step

In [25]:
print(grid_result_actual.best_score_, grid_result_actual.best_params_)

0.9065457778239103 {'activation': 'sigmoid', 'batch_size': 128, 'epochs': 30, 'layers': [64, 32, 16]}

Final Predictions

In [32]:
test_data = pd.read_csv(r'D:\ML Project\Arya assignment\Data set\test_set.csv')

In [33]:
test_data

,Unnamed: 0,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X48,X49,X50,X51,X52,X53,X54,X55,X56,X57
0,0,0.70,0.00,0.70,0.0,0.00,0.00,0.00,0.00,0.00,...,0.00,0.000,0.000,0.000,0.105,0.000,0.000,2.342,47,89
1,1,0.00,0.00,0.84,0.0,0.84,0.00,0.84,0.00,0.00,...,0.00,0.000,0.388,0.000,0.776,0.129,0.000,10.375,168,249
2,2,0.46,0.30,0.46,0.0,0.05,0.12,0.05,0.28,0.43,...,0.00,0.000,0.065,0.000,0.325,0.756,0.153,5.891,193,3040
3,3,0.10,0.20,1.01,0.0,0.80,0.80,0.50,0.00,0.80,...,0.00,0.000,0.110,0.000,0.490,0.158,0.015,8.550,669,1351
4,4,0.00,0.00,0.72,0.0,0.72,0.00,0.72,0.00,0.00,...,0.00,0.000,0.364,0.000,0.729,0.121,0.000,7.781,32,249
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
686,686,0.25,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.25,...,0.00,0.301,0.473,0.043,0.043,0.000,0.000,2.111,17,190
687,687,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,...,2.56,0.000,0.000,0.000,0.375,0.000,0.000,2.250,7,36
688,688,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,...,0.00,0.000,0.000,0.000,0.000,0.000,0.000,2.333,5,7
689,689,0.08,0.08,0.57,0.0,0.48,0.00,0.00,0.08,0.00,...,0.08,0.011,0.034,0.000,0.057,0.022,0.000,1.875,65,542
690,690,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,...,0.00,0.000,0.000,0.000,0.000,0.000,0.000,2.000,4,16

In [34]:
test_data.drop('Unnamed: 0', axis=1, inplace=True)
test_data

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X48,X49,X50,X51,X52,X53,X54,X55,X56,X57
0,0.70,0.00,0.70,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.000,0.000,0.000,0.105,0.000,0.000,2.342,47,89
1,0.00,0.00,0.84,0.0,0.84,0.00,0.84,0.00,0.00,0.00,...,0.00,0.000,0.388,0.000,0.776,0.129,0.000,10.375,168,249
2,0.46,0.30,0.46,0.0,0.05,0.12,0.05,0.28,0.43,0.74,...,0.00,0.000,0.065,0.000,0.325,0.756,0.153,5.891,193,3040
3,0.10,0.20,1.01,0.0,0.80,0.80,0.50,0.00,0.80,0.10,...,0.00,0.000,0.110,0.000,0.490,0.158,0.015,8.550,669,1351
4,0.00,0.00,0.72,0.0,0.72,0.00,0.72,0.00,0.00,0.00,...,0.00,0.000,0.364,0.000,0.729,0.121,0.000,7.781,32,249
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
686,0.25,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.25,0.00,...,0.00,0.301,0.473,0.043,0.043,0.000,0.000,2.111,17,190
687,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,2.56,0.000,0.000,0.000,0.375,0.000,0.000,2.250,7,36
688,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.000,0.000,0.000,0.000,0.000,0.000,2.333,5,7
689,0.08,0.08,0.57,0.0,0.48,0.00,0.00,0.08,0.00,0.00,...,0.08,0.011,0.034,0.000,0.057,0.022,0.000,1.875,65,542
690,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.000,0.000,0.000,0.000,0.000,0.000,2.000,4,16

Random forest model with selected features used as final model for predictions on test data

In [36]:
y_pred = rf_model_actual.best_estimator_.predict(test_data[feature_set])

In [37]:
y_pred

array([0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0], dtype=int64)

In [38]:
len(y_pred)

691

In [42]:
y_pred = pd.DataFrame(y_pred, columns = ['Y_pred'])

In [43]:
y_pred

     Y_pred
0         0
1         1
2         1
3         1
4         1
..      ...
686       0
687       0
688       0
689       0
690       0

[691 rows x 1 columns]

Saving final predictions on test data in csv file

In [45]:
y_pred.to_csv(r"D:\ML Project\Arya assignment\test_predictions.csv")